// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOcUfxKP0bADWz6u0VroQRHcW8wtY2SWU',
    appId: '1:1023709574225:web:dabae5d9b42391a0f47470',
    messagingSenderId: '1023709574225',
    projectId: 'college-project-97221',
    authDomain: 'college-project-97221.firebaseapp.com',
    storageBucket: 'college-project-97221.firebasestorage.app',
    measurementId: 'G-TKHGPS7NQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp3sApTy6nl4poiDsm7CZ8jiXe5fGs0YY',
    appId: '1:1023709574225:android:73976753889823c5f47470',
    messagingSenderId: '1023709574225',
    projectId: 'college-project-97221',
    storageBucket: 'college-project-97221.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOcUfxKP0bADWz6u0VroQRHcW8wtY2SWU',
    appId: '1:1023709574225:web:a708a0496ee943fff47470',
    messagingSenderId: '1023709574225',
    projectId: 'college-project-97221',
    authDomain: 'college-project-97221.firebaseapp.com',
    storageBucket: 'college-project-97221.firebasestorage.app',
    measurementId: 'G-8DV2PGFF72',
  );
}
